services:
  - type: web
    name: mini-crm-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://renderuser:render12345@mini-crm.vs8hoe0.mongodb.net/minicrm?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: minicrm_jwt_secret_key_2024
      - key: NODE_ENV
        value: production

  - type: static
    name: mini-crm-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://final-backend-07ab.onrender.com